name: Android Debug APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 33
          build-tools: '33.0.2'

      - name: Grant execute permission for gradlew
        run: |
          if [ -f ./gradlew ]; then
            chmod +x ./gradlew
          fi

      - name: Use Gradle wrapper or install Gradle if wrapper missing
        run: |
          if [ -f ./gradlew ]; then
            echo "Using gradlew"
          else
            sudo apt-get update
            sudo apt-get install -y wget unzip
            wget https://services.gradle.org/distributions/gradle-7.5.1-bin.zip
            unzip -qq gradle-7.5.1-bin.zip -d /opt/gradle
            echo "export PATH=\$PATH:/opt/gradle/gradle-7.5.1/bin" >> $GITHUB_ENV
          fi

      - name: Build debug APK
        run: ./gradlew clean assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk
